### ISSUE TITLE
R lines do not return data read by an application, but a buffer of all not-yet read data

### ISSUE THREAD

**Issue by otopetrik** [enlyze/PortSniffer#2]
It looks like the `PortSniffer` does not return actual data read by an application using the monitored port.
`PortSniffer` repeatedly returns what looks like some sort of buffer of all data available to be read from the port.
That makes it difficult to reconstruct when an application actually read data from a device.

Running `PortSniffer` from `ENLYZE-PortSniffer-1.2-x86.zip` archive on Win10 32-bit computer with USB connected GSM modem using following command: `PortSniffer-Tool.exe /monitor COM7 RW`

Lines with `W` appear correct.

There seems to be a bug with `R` lines - they are either 1 byte long or 4084 bytes long.
Lines with length 1 often contain correct data, but sometimes one is repeated many (500+) times.
The lines with length 4084 are repeated few times. Most of the line is `00` until the end of line.
Later copies sometimes have few bytes at the beginning removed, and corresponding `00` bytes appended at the end.

It appears that:
- available data (not yet read by an application) are repeatedly returned as `R` lines (that also explains repeated 1 byte lines).
- data are returned as a buffer of all available data (expanded to buffer size used for read with zeros, and capped to about 4k)

Not a windows driver developer, but it looks like:
https://github.com/enlyze/PortSniffer/blob/b690de9819c83d4555d2e5420274c7b170cbd077/src/driver/EnlyzePortSniffer.c#L877
uses the whole provided buffer, which is forwarded here:
https://github.com/enlyze/PortSniffer/blob/b690de9819c83d4555d2e5420274c7b170cbd077/src/driver/EnlyzePortSniffer.c#L852-L853
It ignores the possibility that read request size is different from buffer size - which would explain observed behavior.
(I have no idea if buffer size is determined by the underlying COM port driver or somehow depends on application read request size)

Not sure if overwriting `readWorkItemContext->ReadBufferLength` with something like `min(readWorkItemContext->ReadBufferLength, Params->Parameters.Read.Length)` and possibly renaming to `ReadBufferResponseLength` would be enough or not.

Also not sure if `Params->Parameters.Read.Length` at that point is actually the same value as the original read request's length:
https://github.com/enlyze/PortSniffer/blob/b690de9819c83d4555d2e5420274c7b170cbd077/src/driver/EnlyzePortSniffer.c#L777

**Comment by ColinFinck** [comment]
Hello @otopetrik. Thanks a lot for your bug report!
You are totally right, reads may only be partially completed or not successful at all. PortSniffer 1.2 didn't take that into account.

I have opened a Pull Request in #3, which fixes this issue similar to what you described. I'm using `Params->Parameters.Read.Length` now instead of the buffer length returned by `WdfMemoryGetBuffer`.
To make things clearer, the field in `readWorkItemContext` is now called `BytesRead` instead of `ReadBufferLength`.
I'm also no longer logging unsuccessful reads (with 0 bytes) at all.

Please check the binaries I uploaded in #3. If they fix your problem, this will become PortSniffer 1.3.

**Comment by otopetrik** [comment]
Hello @ColinFinck.
Thanks for the fix and the binaries !

Tried the "ENLYZE-PortSniffer-1.3pre-x86.zip" and **it works**.

Where version 1.2 produced 100+ KiB logs with repeated data, this version produces logs around 10 KiB.
Converted to text, the new/smaller log looks correct - it contains only AT commands written and responses read.

**Comment by ColinFinck** [comment]
Cool! I've just released the final version 1.3 incorporating this fix :)
