### ISSUE TITLE
"R" Command can not work .

### ISSUE THREAD

**Issue by Shazoo** [enlyze/PortSniffer#4]
System : Windows 10 64bit 20H2, boot with "Disable driver signature enforcement"
Hardware : FT232r USB serial port adaptor , which is loop-connected ( RX connected to TX)  as an echo server . 
Software: putty , open with 9600 , works well . ( what I type will been shown, without portsniffer )
application version : 1.3 ; the pull3 :https://github.com/enlyze/PortSniffer/pull/3 ;  the latest version which build by myself . 
 

after the `install`, `attach`, I used this command to monitor:
```
PortSniffer-Tool.exe /monitor COM5 RW
```
putty show only one character and crashed ; portsniffer did not show any "R" log .. 

but the only-write-function worked well : 
```
PortSniffer-Tool.exe /monitor COM5 W
```

```
**********************************************************************
ENLYZE PortSniffer Tool 1.3 (ab820fa0f5e0794861d6297324fa474229c91a1d)
Copyright 2020 Colin Finck, ENLYZE GmbH <c.finck@enlyze.com>
**********************************************************************

W |    1 | 77
W |    1 | 64
W |    1 | 73
W |    1 | 64
W |    1 | 78
W |    1 | 64
W |    1 | 66
W |    1 | 73
W |    1 | 73
W |    1 | 66
W |    1 | 61
W |    1 | 73
W |    1 | 64
W |    1 | 66
W |    1 | 61
W |    1 | 73
W |    1 | 64
W |    1 | 66
W |    1 | 0D
```

**Comment by ColinFinck** [comment]
Confirmed. I replicated your setup here and hit the same problem.

**Comment by ColinFinck** [comment]
I had a try at debugging this problem. For some reason, the completion routine at https://github.com/enlyze/PortSniffer/blob/b3b9ed0520310faef5a3d727575dd01517daf8c4/src/driver/EnlyzePortSniffer.c#L807 is not called.
This happens independently of the Windows version or the USB-Serial adapter used (I tried FTDI and Prolific).

**Comment by Shazoo** [comment]
Thanks very much for your job .

> I had a try at debugging this problem. For some reason, the completion routine at
> 
> https://github.com/enlyze/PortSniffer/blob/b3b9ed0520310faef5a3d727575dd01517daf8c4/src/driver/EnlyzePortSniffer.c#L807
> 
> is not called.
> This happens independently of the Windows version or the USB-Serial adapter used (I tried FTDI and Prolific).

“is not called" .. 
Do you mean :
the `status` (return value) of this 
https://github.com/enlyze/PortSniffer/blob/b3b9ed0520310faef5a3d727575dd01517daf8c4/src/driver/EnlyzePortSniffer.c#L791
and 
https://github.com/enlyze/PortSniffer/blob/b3b9ed0520310faef5a3d727575dd01517daf8c4/src/driver/EnlyzePortSniffer.c#L799
are not NT_SUCCESS ?
or just crashed in 
https://github.com/enlyze/PortSniffer/blob/b3b9ed0520310faef5a3d727575dd01517daf8c4/src/driver/EnlyzePortSniffer.c#L807

I don't know how to debug windows driver in my environment .. Use Virtual Box and passthrough USB to the VM ?

**Comment by ColinFinck** [comment]
All calls in `PortSnifferFilterEvtIoRead` succeed. The call https://github.com/enlyze/PortSniffer/blob/b3b9ed0520310faef5a3d727575dd01517daf8c4/src/driver/EnlyzePortSniffer.c#L807 sets `PortSnifferFilterEvtIoReadCompletionRoutine` as the completion routine to call when the lower driver (the actual serial port or USB-serial adapter driver) has finished reading.

This always worked during my tests. The routine was properly called when new data was read from the serial port.
But for some reason, it does not work in the scenario you describe.

By compiling the driver in debug (checked) mode and watching the debug prints in WinDbg, I can see that `PortSnifferFilterEvtIoRead` is called, but `PortSnifferFilterEvtIoReadCompletionRoutine` is not called.
Stepping through the `PortSnifferFilterEvtIoRead` function also confirms that all its calls succeed.
What I also see is that `PortSnifferFilterEvtIoReadCompletionRoutine` is eventually called when I close the PuTTY session.

Debugging with VirtualBox and USB passthrough works very well. This is what I've used here.

**Comment by ColinFinck** [comment]
@Shazoo Can you try out my PR #4 (the "fix/simultaneous-read-write" branch)?
This one-liner change fixes the problem for me.

**Comment by Shazoo** [comment]
> @Shazoo Can you try out my PR #4 (the "fix/simultaneous-read-write" branch)?
> This one-liner change fixes the problem for me.

It works ! 

Thanks for your job . 
![截图_2021-08-10_09-18-50](https://user-images.githubusercontent.com/3198471/128793829-323dbdc2-32a3-4f3d-9a37-2f2afe6e90cf.png)
